name: Static analysis

on: ["push", "pull_request"]

permissions:
  actions: read
  contents: read
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
      - run: pip install --upgrade pip isort black
      - name: Check import order
        run: isort --profile black --line-length 80 --check pyhanko_eoi*
      - name: Run Black
        run: black -S --line-length 80 --check pyhanko_eoi*
  mypy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: jpetrucciani/mypy-check@0.991
        with:
          path: pyhanko_eoi
          requirements: "-e .[mypy] --config-settings editable_mode=strict"
